trigger:
- main

# Use your self-hosted agent pool
pool:
  name: 'PlaywrightPythonAgent'   # <-- replace with your actual pool name

steps:
  # (Optional) Verify Python version available in your self-hosted agent
  - script: |
      python --version
      pip --version
    displayName: 'Check Python environment'

  - script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    displayName: 'Install dependencies'

  - script: |
      pytest --alluredir=reports/allure-results
    displayName: 'Run tests with Allure reporting'

  # Install Allure CLI (if not pre-installed in agent)
  - script: |
      npm install -g allure-commandline --save-dev
    displayName: 'Install Allure CLI'

  - script: |
      allure generate reports/allure-results -o reports/allure-report --clean
    displayName: 'Generate Allure HTML Report'

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: 'reports/allure-report'
      artifactName: 'allure-report'
      publishLocation: 'Container'
    displayName: 'Publish Allure Report Artifact'
