trigger:
- main   # or your default branch

resources:
  	repositories:
      - repository: Orange-HRM_Playwright-Python
        type: github
        name: Anupama-92/Orange-HRM_Playwright-Python
        endpoint: Anupama-92  # Name of the service connection

pool:
   name: PlaywrightPythonAgent

steps:

  # Step 1: Install dependencies
  - script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    displayName: 'Install dependencies'

  # Step 2: Install Playwright browsers
  - script: |
      python -m playwright install --with-deps
    displayName: 'Install Playwright Browsers'

  # Step 3: Run pytest with Playwright
  - script: |
      pytest --maxfail=1 --disable-warnings -q --junitxml=test-results/results.xml
    displayName: 'Run Pytest Playwright Tests'

  # Step 4: Publish test results in Azure DevOps
  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '**/test-results/results.xml'
      testRunTitle: 'Playwright Python Test Results'
    condition: succeededOrFailed()
